### PR TITLE
Update InboxRecyclerView to v2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by saket**
https://github.com/saket/InboxRecyclerView/pull/34

### CODE REVIEW

**Comment by ZacSweers** [comment]
Thanks, I'll fold these into #172 once 2.0 is released. Note that the current snapshot doesn't reflect all the changes in that PR yet

**Comment by saket** [comment]
@ZacSweers I might have made a few changes after uploading to snapshot. I've re-uploaded the artifacts.

**Comment by saket** [comment]
Do you want me to release a beta build so that you can test it with CatchUp?

**Comment by ZacSweers** [comment]
Let me confirm with a snapshot first before you pull the trigger on it 😬.
Will test tonight if there's an artifact uploaded already

**Comment by saket** [comment]
Aye. Let me know whenever you get time 👍

**Comment by ZacSweers** [comment]
Tested and looks good! I think it'd be good to have some state restoration
APIs as well, but otherwise 2.0 is looking good to me

**Comment by ZacSweers** [comment]
Folding in #172

**Pull request closed without merging**
